name: Docker Image CI

on:
  push:
    branches: [ "armv7" ]
  pull_request:
    branches: [ "armv7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          - name: Checkout main
            uses: actions/checkout@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            
          - name: Build and publish image
            uses: elgohr/Publish-Docker-Github-Action@v5
            with:
              name: junlinwu/kemono-dl # dockerid/imageName
              platforms: linux/arm
              tags: latest
              username: ${{ secrets.DOCKERHUB_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              password: ${{ secrets.DOCKERHUB_TOKEN }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword
